Simplify how it works

diff --git a/gnad b/gnad
--- a/gnad
+++ b/gnad
@@ -1,36 +1,82 @@
-#!/bin/bash
+#!/bin/env bash
+#
+# Manage bootstrap scripts
+
+readonly PROFILE_NAME="${2/\//-}"
+readonly CONFIG_PATH="${HOME}/.config/gnad/profiles"
+readonly PROFILE_PATH="${CONFIG_PATH}/${PROFILE_NAME}"
+
+#######################################
+# Downloads a bootstrap script on the
+# profile folder
+# Globals:
+#   PROFILE_PATH
+# Arguments:
+#   Github repository
+# Returns:
+#   Status
+#######################################
 get(){
-  mkdir -pv "$PROFILE_PATH"
-  git clone --depth 1 "https://github.com/${1}" "$PROFILE_PATH"
+  mkdir -pv "${PROFILE_PATH}"
+  git clone --depth 1 "https://github.com/${1}" "${PROFILE_PATH}"
+  if [[ -d ${PROFILE_PATH}/.git ]]; then
+    echo "Profile installed"
+    return 0
+  else
+    echo "Profile installation failed." >&2
+    return 1
+  fi
 }
 
-enable(){
-  chmod +x "$PROFILE_PATH/install"
-  bash "$PROFILE_PATH/install"
+#######################################
+# Runs a bootstrap script
+# Globals:
+#   PROFILE_PATH
+# Arguments:
+#   None
+# Returns:
+#   Status
+#######################################
+run(){
+  chmod +x "${PROFILE_PATH}/install"
+  if bash "${PROFILE_PATH}/install"; then
+    echo "Script ran successfully"
+    return 0
+  else
+    echo "Script failed." >&2
+    return 1
+  fi
+
 }
 
 list(){
-  ls -1 "$HOME/.config/gnad/profiles/"
+  ls -1 "${HOME}/.config/gnad/profiles/"
 }
 
 remove(){
-  rm -rf "$PROFILE_PATH"
+  rm -rf "${PROFILE_PATH}"
 }
 
+#######################################
+# Updates all the bootstrap scripts
+# Globals:
+#   CONFIG_PATH
+# Arguments:
+#   None
+# Returns:
+#   None
+#######################################
 update(){
-  read -rp "This will override any change you have made to the profile, do you want to continue? (y/N): " answer
-  [[ $answer != "y" ]] && exit
-  for profile in "$CONFIG_PATH"/*; do
-    cd "$CONFIG_PATH/$profile"
+  local answer
+  read -rp "This will override any change you have made to the profile, do you \
+  want to continue? (y/N): " answer
+
+  [[ ${answer} != "y" ]] && return
+
+  for profile in "${CONFIG_PATH}"/*; do
+    cd "${CONFIG_PATH}/${profile}" || exit
     git pull
   done
 }
 
-main(){
-  readonly PROFILE_NAME="${2/\//-}"
-  readonly CONFIG_PATH="$HOME/.config/gnad/profiles"
-  readonly PROFILE_PATH="$CONFIG_PATH/$PROFILE_NAME"
-  "$@"
-}
-
-main "$@"
+"$@"
